version: "3.7"

x-app-volumes: &app-volumes
  - .:/usr/src/app:cached
  - ~/.bash_history:/root/.bash_history

x-app-environment: &app-environment
  - DB_HOST=db
  - DB_NAME=rss_dev
  - DB_USER=postgres

services:
  app:
    build: .
    command: "lein with-profile api ring server"
    volumes: *app-volumes
    environment: *app-environment
    ports:
      - "3000:3000"
      - "4000:4000"
      - "5309:5309"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

  # infra:
  #   build:
  #     context: ./infra
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./infra:/infra

# volumes:
#   bundle_cache:
