apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: ttr-sync
            image: {{ .Values.image }}:{{ .Values.version }}
            command: ["/usr/src/app/ttr-cli"]
            env:
            - name: DB_HOST
              value: ttr-postgresql-headless
            - name: DB_NAME
              value: rss_prod
            - name: DB_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
