apiVersion: v2
name: .
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: 9.3.2
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.local
