name: Build

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      #   with:
      #    driver-opts: image=moby/buildkit:buildx-stable-1

      # - name: Log in to the Container registry
      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build and push api
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: ./Dockerfile
  #         push: true
  #         tags: ${{ env.REGISTRY }}/lukinegor/tg-to-rss:${{ github.sha }}

  # test-image:
  #   runs-on: ubuntu-latest
  #   # container: ghcr.io/lukinegor/tg-to-rss:${{ github.sha }}
  #   container: ghcr.io/lukinegor/tg-to-rss:a7c1f17491f2f88c4efa194fc6e890201a7cef0e
  #   permissions:
  #     contents: read
  #     packages: write
  #   services:
  #     postgres:
  #       image: postgres
  #       env:
  #         POSTGRES_PASSWORD: postgres
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5

  #   steps:
  #     - name: Create db
  #       run: |
  #         cd /usr/src/app

  #         DB_HOST=postgres \
  #           DB_USER=postgres \
  #           DB_PASSWORD=postgres \
  #          DB_NAME=rss_test \
  #           lein run -m rss.db.migrations/create-db

  #     - name: Run migrations
  #       run: |
  #         cd /usr/src/app

  #         DB_HOST=postgres \
  #           DB_USER=postgres \
  #           DB_PASSWORD=postgres \
  #           DB_NAME=rss_test \
  #           lein run -m rss.db.migrations/migrate

  #     - name: Run tests
  #       run: |
  #         cd /usr/src/app

  #         DB_HOST=postgres \
  #           DB_USER=postgres \
  #           DB_PASSWORD=postgres \
  #           DB_NAME=rss_test \
  #           lein test
