name: Create and publish images

on:
  workflow_run:
    workflows: ["Build images"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-image:
    runs-on: ${{ env.REGISTRY }}/tg-to-rss:${{ github.sha }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Run tests
        run: lein tests
