name: Test Image

# on: push

on:
 workflow_run:
    workflows: [Build]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-image:
    runs-on: ubuntu-latest
    # container: ghcr.io/lukinegor/tg-to-rss:${{ github.sha }}
    container: ghcr.io/lukinegor/tg-to-rss:a7c1f17491f2f88c4efa194fc6e890201a7cef0e
    # permissions:
      # contents: read
      # packages: write
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Run tests
        run: |
          cd /usr/src/app

          DB_HOST=postgres \
            DB_USER=postgres \
            DB_PASSWORD=postgres \
            DB_NAME=rss_test \
            lein run -m rss.db.migrations/migrate

          DB_HOST=postgres \
            DB_USER=postgres \
            DB_PASSWORD=postgres \
            DB_NAME=rss_test \
            lein test
