name: Test Image

on: push

# on:
#   workflow_run:
#     workflows: ["Build Image"]
#     types:
#       - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-image:
    # runs-on: ${{ env.REGISTRY }}/lukinegor/tg-to-rss:${{ github.sha }}
    container: ghcr.io/lukinegor/tg-to-rss:aea27bacbd46fbda3e5abcb3198783e1515f7896
    # permissions:
      # contents: read
      # packages: write

    steps:
      - name: Run tests
        run: lein tests
