name: Test Image

on:
  workflow_run:
    workflows: ["Build Image"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-image:
    runs-on: ${{ env.REGISTRY }}/lukinegor/tg-to-rss:${{ github.sha }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Run tests
        run: lein tests
